### ISSUE TITLE
CovPass crash at check validity country selection after travel rules update

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#105]
## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 1.12.0

It is reproducible on other devices running Android 11 as well.

## Describe the bug

CovPass crashes when attempting to select a country other than Germany in the validation screen if the travel rules have been updated.

## Steps to reproduce the issue

In CovPass app

1. Uninstall CovPass app
2. Reinstall CovPass app from Google Play Store
3. Enable flight mode
4. Open CovPass app and run through onboarding
5. Scan 2/2 vaccination certificate
6. Tap "Check validity"
7. Note message "Travel rules not up to date"
8. Tap "Germany" in field "Country"
9. Note that list of countries starting with "Albania" is displayed
10. Close app via recent apps "Close all"
11.  Disable flight mode and ensure Internet availability
12. Open CovPass app
13. Tap "Check validity"
14. Note that message "Travel rules not up to date" is no longer displayed
15. Tap "Germany" in field "Country"
16. App crashes

## Expected behavior

1. The app should not crash. It should allow selection of another country other than Germany.
2. External data should not be able to crash the app. If there is an error in downloaded travel rules, it should cause an error message to be output and the app should fail gracefully.

## Additional context

Logcat:

```
? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.rki.covpass.app, PID: 2515
    android.content.res.Resources$NotFoundException: Drawable de.rki.covpass.app:drawable/flag_rs with resource ID #0x7f0700db
    Caused by: android.content.res.Resources$NotFoundException: File res/Nw.xml from drawable resource ID #0x7f0700db
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:837)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:891)
        at android.content.res.Resources.getDrawable(Resources.java:833)
        at android.content.Context.getDrawable(Context.java:605)
        at androidx.core.content.a$c.b(Unknown Source:0)
        at androidx.core.content.a.d(Unknown Source:6)
        at androidx.appcompat.widget.m0.k(Unknown Source:16)
        at androidx.appcompat.widget.m0.j(Unknown Source:2)
        at h.a.d(Unknown Source:4)
        at androidx.appcompat.widget.m.g(Unknown Source:8)
        at androidx.appcompat.widget.n.setImageResource(Unknown Source:4)
        at u8.d$a.O(Unknown Source:32)
        at u8.d.D(Unknown Source:37)
        at u8.d.l(Unknown Source:2)
        at androidx.recyclerview.widget.RecyclerView$g.m(Unknown Source:0)
        at androidx.recyclerview.widget.RecyclerView$g.c(Unknown Source:29)
        at androidx.recyclerview.widget.RecyclerView$v.H(Unknown Source:39)
        at androidx.recyclerview.widget.RecyclerView$v.I(Unknown Source:413)
        at androidx.recyclerview.widget.RecyclerView$v.p(Unknown Source:5)
        at androidx.recyclerview.widget.RecyclerView$v.o(Unknown Source:1)
        at androidx.recyclerview.widget.LinearLayoutManager$c.d(Unknown Source:11)
        at androidx.recyclerview.widget.LinearLayoutManager.s2(Unknown Source:0)
        at androidx.recyclerview.widget.LinearLayoutManager.U1(Unknown Source:38)
        at androidx.recyclerview.widget.LinearLayoutManager.X0(Unknown Source:356)
        at androidx.recyclerview.widget.RecyclerView.E(Unknown Source:38)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:65)
        at android.view.View.measure(View.java:23300)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:23300)
        at androidx.core.widget.NestedScrollView.measureChildWithMargins(Unknown Source:38)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.core.widget.NestedScrollView.onMeasure(Unknown Source:0)
        at android.view.View.measure(View.java:23300)
        at androidx.constraintlayout.widget.ConstraintLayout$c.b(Unknown Source:528)
        at q0.b.a(Unknown Source:104)
        at q0.b.b(Unknown Source:157)
        at q0.b.d(Unknown Source:269)
        at p0.f.H1(Unknown Source:23)
        at androidx.constraintlayout.widget.ConstraintLayout.v(Unknown Source:135)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:71)
        at android.view.View.measure(View.java:23300)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23300)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
        at android.view.View.measure(View.java:23300)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:23300)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23300)
? W/ActivityManager: crash : de.rki.covpass.app,0
? W/ActivityManager:   Force finishing activity de.rki.covpass.app/.main.MainActivity
```

**Comment by MikeMcC399** [comment]
The same version of the app (1.12.0) does not crash on an Android 11 tablet (which has a larger screen than the smartphones where the app crashed).

`flag_rs` noted in the crash dump seems to be the flag for Serbia and this country was not listed under the countries displayed on the tablet under "Choose destination".

**Comment by MikeMcC399** [comment]
The tablet crashed as well with the repro steps after I uninstalled CovPass and re-installed (Version 1.12.0).

**Comment by MikeMcC399** [comment]
It looks like there is a problem related to updated travel rules:

## Steps to reproduce:

In CovPass app

1. Uninstall CovPass app
2. Reinstall CovPass app from Google Play Store
3. Enable flight mode
4. Run through onboarding
5. Scan 2/2 vaccination certificate
6. Tap "Check validity"
7. Note message "Travel rules not up to date"
8. Tap "Germany" in field "Country"
9. Note that list of countries starting with "Albania" is displayed
10. Close app via recent apps "Close all"
11.  Disable flight mode and ensure Internet availability
12. Open CovPass app
13. Tap "Check validity"
14. Note that message "Travel rules not up to date" is no longer displayed
15. Tap "Germany" in field "Country"
16. App crashes

**Comment by pucherd** [comment]
Hello, thank you for reporting the bug. We are analysing it and a hotfix version will be released soon.

**Comment by sdruskat** [comment]
Another confirmation for Android 10 QKQ1.200114.002 and CovPass 1.12.0 from Google Play Store.

**Comment by MikeMcC399** [comment]
@pucherd 
Do you have any timeline to resolve this issue?

I tried replacing the very large (1.6MB) [flag_rs.xml](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/release/1.12.x/common-app-covpass/src/main/res/drawable-anydpi/flag_rs.xml) using another flag in an Android Studio build and the app then didn't crash.

**Comment by JilAuraya** [comment]
Hello :) Thank you for reporting the bug! We already created a fix which now goes through the usual review processes. We are eager to put it out asap! Please bear with us.

**Comment by MikeMcC399** [comment]
CovPass Android 1.13.2 does not crash.

1. Scan 2/2 vaccination certificate
2. Tap "Check validity"
3. Tap "Germany" in field "Country"
4. Note that list of countries starting with "Albania" is displayed

App does not crash at this point, therefore now closing this issue.
